### ISSUE TITLE
エンジンビルド後のテストがmacOSで落ちる

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#1191]
## 不具合の内容

エンジンをビルドした後に自動で走るrelease-test workflowがmacOSでだけ落ちてたのでとりあえずissueを作りました。
実際にエンジンをダウンロードして使ってみた感じはまともに動きました。

ちゃんと調べてなくてただの予想ですが、github actionsのmacosのスペックが縮小されたんじゃないかなと思ってます。
最近macos-latestが更新されたあたりにエディタ側もスペック不足が原因っぽいエラーがでてたので･･･。
https://github.com/VOICEVOX/voicevox/issues/2007

### 現象・ログ

Github Workflowの結果↓
https://github.com/VOICEVOX/voicevox_engine/actions/runs/8852174690

ログ↓
```log
Run python build_util/check_release_build.py --dist_dir dist/
Warning: cpu_num_threads is set to 0. Setting it to half of the logical cores.
INFO:     Started server process [3165]
INFO:     Waiting for application startup.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 942, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/work/voicevox_engine/voicevox_engine/build_util/check_release_build.py", line 72, in <module>
    test_release_build(dist_dir=args.dist_dir, skip_run_process=args.skip_run_process)
  File "/Users/runner/work/voicevox_engine/voicevox_engine/build_util/check_release_build.py", line 32, in test_release_build
    with urlopen(req) as res:
         ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
Error: Process completed with exit code 1.
```
## その他

とりあえずエンジンの起動待機時間を長くすれば解決できるのではと楽観的に考えてます。

**Comment by Hiroshiba** [comment]
ちょっと調べてみています。

- https://github.com/VOICEVOX/voicevox_engine/pull/1203

何をどうやっても落ちるのでtmateで中に入ってみたらSegmentation Fault 11が出ていることが分かりました 😇 
`--enable_mock`を指定して起動しても落ちるので、何かそもそも足りてないかも･･･？

引き続き調査しています。

**Comment by Hiroshiba** [comment]
macos-11だけなぜか動かないということがわかりました 😇 
そしてなぜか0.18.0エンジンはmacos-11でも動きました。

どのバージョンもビルドはmacos-11でやってるはず。まあなにか構成が変わった･･･？

いろんなmacos環境でエンジンをダウンロードして検証するコードです。（ずっと稼働するので適宜停止が必要）
<details>

```yaml
name: check test

defaults:
  run:
    shell: bash

on:
  push:

env:
  REPO_URL: "https://github.com/VOICEVOX/voicevox_engine"
  VERSION: "0.19.0"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            target: macos-x64
          - os: macos-12
            target: macos-x64
          - os: macos-13
            target: macos-x64
          - os: macos-14
            target: macos-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: <Setup> Declare variables
        id: vars
        run: |
          echo "release_url=${{ env.REPO_URL }}/releases/download/${{ env.VERSION }}" >> "$GITHUB_OUTPUT"
          echo "package_name=voicevox_engine-${{ matrix.target }}-${{ env.VERSION }}" >> "$GITHUB_OUTPUT"

      - name: <Setup> Download ENGINE package
        run: |
          mkdir -p download
          curl -L -o "download/list.txt" "${{ steps.vars.outputs.release_url }}/${{ steps.vars.outputs.package_name }}.7z.txt"
          cat "download/list.txt" | xargs -I '%' curl -L -o "download/%" "${{ steps.vars.outputs.release_url }}/%"
          7z x "download/$(head -n1 download/list.txt)"
          mv "${{ matrix.target }}" dist/

      - name: <Setup> Set up permission
        if: startsWith(matrix.target, 'linux') || startsWith(matrix.target, 'macos')
        run: chmod +x dist/run

      - name: run dist/run
        run: ./dist/run
```

</details>

**Comment by Hiroshiba** [comment]
macos-11は`6/28/2024`でGithub Workflowで使えなくなるとのことなので、もうサポート辞めるのが良いのかなと思いました！！
macos-12にしましょう･･･！！（今Github Actionsにある最新が14）

その方針でプルリクエストを作ってみます。
