### ISSUE TITLE
bug: ビルド系 CI が `filemap` 関係で失敗する

### ISSUE THREAD

**Issue by tarepan** [VOICEVOX/voicevox_engine#1423]
## 不具合の内容
GitHub Actions でのビルド系 CI が失敗している。  

#1318 で導入された `generate_filemap.py` が関係している模様。  
C.C. @sabonerune @Hiroshiba  

### 現象・ログ
https://github.com/VOICEVOX/voicevox_engine/actions/runs/9632944954/job/26566758289
```
------
 > [linux/amd64 runtime-env 21/24] RUN gosu user /opt/python/bin/python3 /tmp/generate_filemap.py --target_dir resources/character_info:
0.358 Traceback (most recent call last):
0.358   File "/tmp/generate_filemap.py", line 62, in <module>
0.358     save_path.write_text(json.dumps(path_to_hash, ensure_ascii=False), encoding="utf-8")
0.358   File "/opt/python/lib/python3.11/pathlib.py", line 1078, in write_text
0.359     with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
0.359          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.359   File "/opt/python/lib/python3.11/pathlib.py", line 1044, in open
0.359     return io.open(self, mode, buffering, encoding, errors, newline)
0.359            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.359 PermissionError: [Errno 13] Permission denied: 'resources/character_info/filemap.json'
------
Dockerfile:263
--------------------
 261 |     # Generate filemap.json
 262 |     ADD ./tools/generate_filemap.py /tmp/
 263 | >>> RUN gosu user /opt/python/bin/python3 /tmp/generate_filemap.py --target_dir resources/character_info
 264 |     
 265 |     # Keep this layer separated to use layer cache on download failed in local build
--------------------
ERROR: failed to solve: process "/bin/sh -c gosu user /opt/python/bin/python3 /tmp/generate_filemap.py --target_dir resources/character_info" did not complete successfully: exit code: 1
```

### 再現手順
ビルド系 CI を実行する。  

### 期待動作
ビルドが成功する。

## VOICEVOXのバージョン
0.19.0

**Comment by sabonerune** [comment]
恐らく書き込み先の`resources/character_info`に書き込むためにroot権限が必要なのだと思います。
`gosu user`を外してroot権限で実行すれば問題は解決すると思います。

**Comment by Hiroshiba** [comment]
そもそも`resources/character_info`ではなく`/opt/voicevox_engine/resources/character_info`に向けて実行すべきかもしれない･･･？

**Comment by Hiroshiba** [comment]
toolsへのコピーもこの辺りに移動したほうが良いかも
https://github.com/VOICEVOX/voicevox_engine/blob/3c30f301e2414e361aa22186fae0163ee19b5e55/Dockerfile#L234-L235

**Comment by Hiroshiba** [comment]
@sabonerune すみません！
レビュー漏れだったので申し訳ないのですが、修正PRお願いしてもよいでしょうか 🙇 

ADD toolsの移動と、あとresourcesのパスを正しくすればたぶん動く気がしています。
github actions上でdocker bulidしてみるチェックもいただけると心強いですが、それなしでもたぶん通るのでOKです！！
