### ISSUE TITLE
Dockerで起動しようとするとエラーになる。

### ISSUE THREAD

**Issue by hirasaki1985** [VOICEVOX/voicevox_engine#1491]
担当者様

以下質問させていただきます。

## 質問の内容

dockerで本リポジトリを起動したいと思っております。
README.mdに沿って実行したところ以下のようなエラーがでました。

```
$ docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest
$ docker run --rm -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest

...

https://blog.nicovideo.jp/niconews/224589.html
+ exec gosu user /opt/python/bin/python3 ./run.py --voicelib_dir /opt/voicevox_core/ --runtime_dir /opt/onnxruntime/lib --host 0.0.0.0
Warning: cpu_num_threads is set to 0. Setting it to half of the logical cores.
Info: Loading core 0.15.5.
Traceback (most recent call last):
  File "/opt/voicevox_engine/./run.py", line 414, in <module>
    main()
  File "/opt/voicevox_engine/./run.py", line 367, in main
    preset_manager = PresetManager(preset_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/voicevox_engine/voicevox_engine/preset/preset_manager.py", line 38, in __init__
    self.preset_path.write_text("[]")
  File "/opt/python/lib/python3.11/pathlib.py", line 1078, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/voicevox_engine/presets.yaml'
```

presets.yamlを作成してパスを指定してもエラーが起きて起動できません。

```
$  $ docker run --rm -p '127.0.0.1:50021:50021' \
  -v $(pwd)/presets.yaml:/opt/voicevox_engine/presets.yaml \
  voicevox/voicevox_engine:latest \
  --preset_path /opt/voicevox_engine/presets.yaml

...

利用規約の詳細は以下をご確認ください。
https://blog.nicovideo.jp/niconews/224589.html
+ exec --preset_path /opt/voicevox_engine/presets.yaml
/entrypoint.sh: line 7: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

渡しの開発環境は以下の通りです。
```
 $ docker -v
Docker version 27.3.1, build ce12230

macOS Sequoia 15.1.1

```

お時間ある時で良いので、確認よろしくお願いいたします。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
プリセットファイルへの書き込み権限がないことが原因そうです。
プリセットファイルのパスに書き込み可能な適当な場所を指定すると解決するかもしれません。

プリセットファイルのパスは`--preset_path`でも変更可能ですが、`VV_PRESET_FILE`環境変数で変更可能です。
例えば`docker run`する際に`-e VV_PRESET_FILE:/tmp/preset.yml`などを追加すると一旦迂回できると思います。

**Comment by hirasaki1985** [comment]
@Hiroshiba 
ご返信ありがとうございます。
以下のコマンドで動作しました！ありがとうございました。
```
$ docker run --rm -v ./presets.yaml:/opt/voicevox_engine/presets.yaml \
     -p '127.0.0.1:50021:50021' \
     -e VV_PRESET_FILE:/opt/voicevox_engine/presets.yaml \
     voicevox/voicevox_engine:cpu-ubuntu20.04-latest
```
