### ISSUE TITLE
/mora_dataにアクセスするとエラーになる

### ISSUE THREAD

**Issue by qwerty2501** [VOICEVOX/voicevox_engine#238]
## 不具合の内容

run.pyにてSynthesisEngine.replace_mora_dataを直接読んでいる箇所があるが、疑問文自動化対応でいれた引数が追加されていないのでエラーになる

### エラーログ
```bash
[21:29:12.481] [info]  ENGINE: INFO:     127.0.0.1:58416 - "POST /mora_data?speaker=2 HTTP/1.1" 500 Internal Server Error
[21:29:12.482] [error] ENGINE: ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "/home/qwerty2501/.asdf/installs/python/3.8.12/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 743, in run
    result = func(*args)
  File "run.py", line 207, in mora_data
    return engine.replace_mora_data(accent_phrases, speaker_id=speaker)
TypeError: replace_mora_data() missing 2 required positional arguments: 'fcl_accent_phrases' and 'enable_interrogative'
```

### 再現手順

起動して /mora_dataにアクセスする

### 期待動作

/mora_data にアクセスしてもエラーにならずにAccentPhraseを返せること

**Comment by qwerty2501** [comment]
replace_mora_dataを直接呼び出してるところがあるとは思ってなかったので想定外でした。
これだと model.pyの　`AccentPhrase`　にis_interrogativeをもたせたほうが良いような気がしましたがどうでしょう

**Comment by Hiroshiba** [comment]
おっと！なるほどです。気づき＆報告感謝です！！

仕組み上、modelの`AccentPhrase`に`is_interrogative`はなくても良いはずなので、たぶん無いほうがロジックがきれいになりそうだなと思います。
コードを見てみましたが、`replace_mora_data`の引数に`enable_interrogative`が必要になっているのをなんとかできそうです。
`create_accent_phrases`内で呼ぶ`replace_mora_data`の返り値に`adjust_~`をする形を想像しました。

**Comment by Hiroshiba** [comment]
マージされたからclose！
