### ISSUE TITLE
dockerでの話者名がおかしい・docker GPU版で音声合成するとエラーが発生する

### ISSUE THREAD

**Issue by kuroneko6423** [VOICEVOX/voicevox_engine#312]
## 質問の内容

dockerで起動しているのですが名前が
 style0dummy1, style1dummy1, style2dummy1, style3dummy1, style0dummy2, style1dummy2, style2dummy2, style3dummy2
になっています。そして音声合成が行われません。

## VOICEVOXのバージョン

0.9.5

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

Ubuntu Server 20.04 LTS

**Comment by Hiroshiba** [comment]
issueありがとうございます！

> 名前が
> style0dummy1, style1dummy1, style2dummy1, style3dummy1, style0dummy2, style1dummy2, style2dummy2, style3dummy2

こちらですが、いまのところdocker版はダミーデータが使われるようになっているので、現状の仕様となります。
こちらのissueが関連しそうです。（もし可能なら取り組んでみて頂けるととても嬉しいです！）

- https://github.com/VOICEVOX/voicevox_engine/issues/278

> そして音声合成が行われません。

[こちらのissue](https://github.com/VOICEVOX/voicevox_engine/issues/308)でもお伺いしましたが、一般に問題が起こった際はそのエラーログを添付して頂くと話がスムーズになります。
今回もエラーログを添付してください！

ちなみにgithubでは、

<pre>
```bash
コマンド
```
</pre>

のように囲うとコードが読みやすくなったりします。

**Comment by kuroneko6423** [comment]
音声合成をしようとしたら

```bash
INFO:     172.17.0.1:55874 - "POST /audio_query?text=%E6%8E%A5%E7%B6%9A%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82&speaker=3 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/user/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 743, in run
    result = func(*args)
  File "./run.py", line 176, in audio_query
    accent_phrases = create_accent_phrases(text, speaker_id=speaker)
  File "./run.py", line 83, in create_accent_phrases
    return engine.replace_mora_data(
AttributeError: 'SynthesisEngine' object has no attribute 'replace_mora_data'
```

**Comment by takana-v** [comment]
こちらで検証したところ、libtorchの読み込みでエラーが出ているようです。
現在のバージョンではlibtorchからonnxruntimeに移行しているため、最新版では問題が発生しないと思われます。
最新バージョンをお試しください。

ログ：

```
Traceback (most recent call last):
  File "/opt/voicevox_engine/voicevox_engine/synthesis_engine.py", line 523, in make_synthesis_engine
    import core
ImportError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
Notice: mock-library will be used. Try re-run with valid --voicevox_dir
```

**Comment by kuroneko6423** [comment]
最新バージョンの0.9.5なのですが...

**Comment by Hiroshiba** [comment]
おお、なるほどです、調査ありがとうございます…！

@kuroneko6423 ちょうど先日新しいバージョンをプレリリースしました！
0.10.2があると思います、こちらだといかがでしょう👀

**Comment by kuroneko6423** [comment]
了解です。やってみます

**Comment by kuroneko6423** [comment]
起動したら

```bash
root@KuronekoServer-Server2:~# docker run  --gpus all -p '127.0.0.1:50021:50021' hiroshiba/voicevox_engine:nvidia-ubuntu20.04-0.10.2
+ cat /opt/voicevox_core/README.txt
これは「四国めたん」「ずんだもん」「春日部つむぎ」「雨晴はう」「波音リツ」の VOICEVOX コアライブラリです。
https://github.com/Hiroshiba/voicevox_core


## 許諾内容

1. 商用・非商用問わず利用することができます
2. アプリケーションに組み込んで再配布することができます
3. 作成された音声を利用する際は、「音声ライブラリの利用規約」に従ってください
4. 作成された音声の利用を他者に許諾する際は、当該他者に対し本許諾内容の 3 及び 4 を義務付けてください


## 音声ライブラリの利用規約

### 四国めたん・ずんだもん

四国めたん・ずんだもんの音声ライブラリを用いて生成した音声は、
「VOICEVOX:四国めたん」「VOICEVOX:ずんだもん」とそれぞれクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://zunko.jp/con_ongen_kiyaku.html

### 春日部つむぎ

春日部つむぎの音声ライブラリを用いて生成した音声は、
「VOICEVOX:春日部つむぎ」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://tsukushinyoki10.wixsite.com/ktsumugiofficial/%E5%88%A9%E7%94%A8%E8%A6%8F%E7%B4%84

### 波音リツ

波音リツの音声ライブラリを用いて生成した音声は、
「VOICEVOX:波音リツ」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
http://canon-voice.com/kiyaku.html

## 禁止事項

- 逆コンパイル・リバースエンジニアリング及びこれらの方法の公開すること
- 製作者または第三者に不利益をもたらす行為
- 公序良俗に反する行為


## 免責事項

本ソフトウェアにより生じた損害・不利益について、製作者は一切の責任を負いません。


## その他

ご利用いただいた際には、VOICEVOX を利用したことがわかるように
[ホームページ](https://voicevox.hiroshiba.jp/)へのリンクを記載いただけると幸いです。

© 2021 Hiroshiba Kazuyuki
+ exec gosu user /opt/python/bin/python3 ./run.py --use_gpu --voicelib_dir /opt/voicevox_core/ --host 0.0.0.0
2022-01-29 16:13:25.172706325 [E:onnxruntime:, inference_session.cc:1448 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cublasStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cublasStatus_t; bool THRW = true] CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=f7957bc2f5dd ; expr=cublasCreate(&cublas_handle_); 


Traceback (most recent call last):
  File "./run.py", line 505, in <module>
    make_synthesis_engine(
  File "/opt/voicevox_engine/voicevox_engine/synthesis_engine/make_synthesis_engine.py", line 61, in make_synthesis_engine
    core.initialize(voicelib_dir.as_posix() + "/", use_gpu, cpu_num_threads or 0)
  File "core/_core.pyx", line 7, in core._core.initialize
  File "core/_core.pyx", line 17, in core._core.initialize
Exception: ONNX raise exception: Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cublasStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cublasStatus_t; bool THRW = true] CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=f7957bc2f5dd ; expr=cublasCreate(&cublas_handle_); 
```

**Comment by kuroneko6423** [comment]
こうなりました

**Comment by Hiroshiba** [comment]
なるほどです！
エラー内容的にcuda周りのエラーだと思われますが、docker上でcudaを使う他のソフトウェアなどは動きますか？
（VOICEVOX側の問題か、環境側の問題かを切り分けたいので聞いてみました）

**Comment by kuroneko6423** [comment]
testしたことはありませんね()

**Comment by kuroneko6423** [comment]
cudaとNVIDIAドライバーは入れてます
```bash
root@KuronekoServer-Server2:~# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by HyodaKazuaki** [comment]
> Exception: ONNX raise exception: Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cublasStatus_t; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cublasStatus_t; bool THRW = true] CUBLAS failure 3: CUBLAS_STATUS_ALLOC_FAILED ; GPU=0 ; hostname=f7957bc2f5dd ; expr=cublasCreate(&cublas_handle_); 

`CUBLAS_STATUS_ALLOC_FAILED`と出ていますが、GPUの上にすでに何か別のプロセスが存在していませんか？
`nvidia-smi`コマンドを使ってメモリを大量に確保しているプロセスがないか確認してみてください。
もしかするとGPUメモリ(VRAM)が足りないのかもしれません。

**Comment by kuroneko6423** [comment]
nvidia-smiの結果です
```bash
root@KuronekoServer-Server2:~# nvidia-smi
Sat Jan 29 16:50:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.94       Driver Version: 470.94       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:02:00.0 N/A |                  N/A |
| 10%   29C    P8    N/A /  N/A |      1MiB /  1998MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:03:00.0 N/A |                  N/A |
| 10%   24C    P8    N/A /  N/A |      1MiB /  2000MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by kuroneko6423** [comment]
前Windows版ではGPU版できたのでメモリはないと思いますが...

**Comment by HyodaKazuaki** [comment]
Docker上で`nvidia-smi`コマンドは使えますか？
また、Docker上でNVIDIAのサンプルコンテナ(N体問題をシミュレーションするプログラムなど)が実行できるかも確認してみてください。
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/k8s/containers/cuda-sample

**Comment by kuroneko6423** [comment]
```bash
root@KuronekoServer-Server2:~#  docker run --rm --gpus all nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
Unable to find image 'nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2' locally
vectoradd-cuda10.2: Pulling from nvidia/k8s/cuda-sample
171857c49d0f: Pull complete 
419640447d26: Pull complete 
61e52f862619: Pull complete 
c118dad7e37a: Pull complete 
29c091e4be16: Pull complete 
d85c81a4428d: Pull complete 
13463320fb92: Pull complete 
a0a71ed83844: Pull complete 
Digest: sha256:4593078cdb8e786d35566faa2b84da1123acea42f0d4099e84e2af0448724af1
Status: Downloaded newer image for nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done
```

**Comment by Hiroshiba** [comment]
うーん…なるほどです。

エラー内容はgpuメモリ確保エラーですよね、gpuメモリ2GBだと足りないとか…？
であれば、起動しながら、gpuメモリ使用量を見てみると何かわかるかもと思いました。

たぶん @kuroneko6423 さんの環境は @kuroneko6423 さんが最も詳しいので、いろいろ調査していただけるととても助かります…！

**Comment by kuroneko6423** [comment]
> うーん…なるほどです。
> 
> エラー内容はgpuメモリ確保エラーですよね、gpuメモリ2GBだと足りないとか…？
> であれば、起動しながら、gpuメモリ使用量を見てみると何かわかるかもと思いました。
> 
> たぶん @kuroneko6423 さんの環境は @kuroneko6423 さんが最も詳しいので、いろいろ調査していただけるととても嬉しいです…！

了解です。
少し調べてみます

**Comment by Hiroshiba** [comment]
@kuroneko6423 
その後どうでしょう？👀

**Comment by kuroneko6423** [comment]
いろいろ試してみたのですがやはり無理ですね。
2GBのGPU2つやっても動作できませんね。
CPUだと行けます

**Comment by Hiroshiba** [comment]
おっと、なるほどです。
こちらのコメントで紹介してくださったnvidia-smiは試されましたか？
https://github.com/VOICEVOX/voicevox_engine/issues/312#issuecomment-1024953905

**Comment by kuroneko6423** [comment]
動きはしましたがVOICEVOXの処理は無理でしたね

**Comment by Hiroshiba** [comment]
なるほどです。
ちなみにdockerコンテナ上で試された感じでしょうか？
メモリ量の不足が原因であれば、実行時に`docker exec`を経由してnvidia-smiをwatchなどで実行し続けてメモリ使用量の推移を計測するとなにかわかるかもしれません。
もしよければいろいろ試された結果を記載いただけると、後の方々の助けになるかもしれません。

**Comment by kuroneko6423** [comment]
ごめんなさい。今日友人にテスト機を渡してしまいました
