### ISSUE TITLE
500 Internal Server Error (UnicodeDecodeError: 'utf-8' codec can't decode byte ~)

### ISSUE THREAD

**Issue by kuroneko6423** [VOICEVOX/voicevox_engine#488]
## 不具合の内容

utf-8のバグ?

### 現象・ログ

```
INFO:     192.168.1.40:38210 - "POST /synthesis?speaker=3 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\fastapi\applications.py", line 208, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\applications.py", line 112, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\middleware\errors.py", line 159, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\middleware\cors.py", line 84, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\exceptions.py", line 71, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\routing.py", line 656, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\routing.py", line 259, in handle
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\routing.py", line 61, in app
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\fastapi\routing.py", line 226, in app
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\fastapi\routing.py", line 161, in run_endpoint_function
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\concurrency.py", line 39, in run_in_threadpool
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\anyio\to_thread.py", line 28, in run_sync
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\anyio\_backends\_asyncio.py", line 743, in run
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\run.py", line 300, in synthesis
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\voicevox_engine\synthesis_engine\synthesis_engine_base.py", line 234, in synthesis
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\voicevox_engine\synthesis_engine\synthesis_engine.py", line 483, in _synthesis_impl
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\voicevox_engine\synthesis_engine\core_wrapper.py", line 495, in decode_forward
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 219: invalid start byte
```
### 再現手順

apiに読み上げのリクエストをずっとし続ける。
再起動をしたら治る。

### 期待動作

500 Internal Server Errorが出ない

## VOICEVOXのバージョン

0.13.1

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

なし

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

エラー内容を素直に解釈すると、「不正なテキストが来た」のが原因なのかなと思いました。
どういったテキストのリクエストでエラーが出ましたか？

**Comment by kuroneko6423** [comment]
同じ現象がまた近々発生すると思うのでその際に送らさせていただきます。

**Comment by Hiroshiba** [comment]
ありがとうございます！
原因の切り分けができると話が進みやすいので、その際は↓の項目の結果もあると嬉しいです･･･！

* テキストは何か
* 同じリクエストを送るとどうか
* 他のリクエストを送るとどうか
* メモリ使用量・GPUメモリ使用量・ストレージ容量に異常はないか

**Comment by kuroneko6423** [comment]
テキストじゃないやつのエラーもあったので一応貼っておきます。

```2022-10-16 16:46:02.4727984 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running MemcpyToHost node. Name:'Memcpy_token_61' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1740)\onnxruntime.dll!00007FFA9A56DDEC: (caller: 00007FFA9A96F080) Exception(3) tid(86fc) 887A0005 GPU デバイス インスタンスが中断されています。GetDeviceRemovedReason を使用して適切なアクションを確認してください。```

VRAM: 約6GB使用
メモリ使用: 約4GB
ストレージ: 全てのディスクに100GB以上空きあり

**Comment by Hiroshiba** [comment]
ありがとうございます！
お使いのPCのスペックはどうでしょうか？
（メモリ4GBのうち4GB使用中なのと、メモリ8GBのうち4GB使用中なのでは話が結構変わってきそうだなと）

**Comment by kuroneko6423** [comment]
VRAMは12GBです。
RAMは24GBです。

**Comment by Hiroshiba** [comment]
なるほどです、メモリ不足によるエラーではなさそうですね･･･　ありがとうございます！

>  GPU デバイス インスタンスが中断されています

**Comment by sabonerune** [comment]
UnicodeDecodeErrorの原因は`core.decode_forward()`が失敗したのでエラーメッセージを読みだしたらUTF-8でデコードできなかったことだと思います。
https://github.com/VOICEVOX/voicevox_engine/blob/45f7c58f7b92dd03675958de26d685c3a2affeba/voicevox_engine/synthesis_engine/core_wrapper.py#L494-L495

本来のエラーメッセージは別物と思われます。

**Comment by kuroneko6423** [comment]
```INFO:     192.168.1.40:49726 - "POST /audio_query?text=%E3%81%8A%E3%81%AF%E3%82%88%E3%81%86&speaker=3 HTTP/1.1" 200 OK
INFO:     192.168.1.40:49726 - "POST /synthesis?speaker=3 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\fastapi\applications.py", line 208, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\applications.py", line 112, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\middleware\errors.py", line 159, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\middleware\cors.py", line 84, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\exceptions.py", line 71, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\routing.py", line 656, in __call__
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\routing.py", line 259, in handle
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\routing.py", line 61, in app
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\fastapi\routing.py", line 226, in app
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\fastapi\routing.py", line 161, in run_endpoint_function
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\starlette\concurrency.py", line 39, in run_in_threadpool
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\anyio\to_thread.py", line 28, in run_sync
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\anyio\_backends\_asyncio.py", line 743, in run
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\run.py", line 300, in synthesis
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\voicevox_engine\synthesis_engine\synthesis_engine_base.py", line 234, in synthesis
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\voicevox_engine\synthesis_engine\synthesis_engine.py", line 483, in _synthesis_impl
  File "C:\Users\kuroneko\AppData\Local\Programs\VOICEVOX\voicevox_engine\synthesis_engine\core_wrapper.py", line 495, in decode_forward
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 221: invalid start byte```

VRAM: 約3GB使用
メモリ使用: 約3GB
ストレージ: 全てのディスクに100GB以上空きあり

error中
Q. 同じリクエストを送るとどうか
Y. 500error
Q. 他のリクエストを送るとどうか
A. 500error
再起動後
Q. 同じリクエストを送るとどうか
Y. 何もerror等発生しない
Q. 他のリクエストを送るとどうか
A. 通常通り動く

**Comment by kuroneko6423** [comment]
ログをtxt等で保存する方法とかありますか？
過去のログが見れないので()

**Comment by sabonerune** [comment]
@kuroneko6423 エディタから起動している場合は`%APPDATA%/voicevox/logs/`に保存されていますがそうでない場合は`stdout/stderr`から出力されるだけですね。

これからシェルを使って起動するときに保存したいという意味ならリダイレクトやteeを使うことになりますね。

**Comment by kuroneko6423** [comment]
Windowsで
```
run.exe --use_gpu --host=0.0.0.0 --port=50021
```
で実行しています。

あと、stdout/stderrとは何でしょうか()

**Comment by Hiroshiba** [comment]
@kuroneko6423 詳細なスペックと検証、本当にありがとうございます！！
他のリクエストもエラーで、かつ再起動後に同じリクエストが通るということは、リクエストが特殊なのではなく、問題がエンジン側にある感じですね･･･。

そして @sabonerune さんもありがとうございます！！
エラーメッセージ取得時にエラーが出ているという視点は盲点でした！！
PRもありがとうございます、正しいエラーが見れそうです！

**Comment by Hiroshiba** [comment]
@kuroneko6423 さん
いろいろありがとうございます。
一旦解決策ですが、もしかしたら`use_gpu`を指定しなければ発生しないかもしれません。

また、最近「エンジンがオンボードのGPUを使ってしまうから不具合が出る」という報告をちらほら頂いています。
同じような報告か確認したくてお伺いしたいのですが、タスクマネージャーに表示されるこの欄は「GPU 0」以外のGPUが表示されていたりしますか？
<img width="100" src="https://user-images.githubusercontent.com/4987327/196227867-721935a9-eaa5-4377-8596-0b8f1767e70e.png" />
また表示されていた場合、使いたいGPUは「GPU 0」以外だったりされますか？

**Comment by kuroneko6423** [comment]
GPU0: GT1030
GPU1: RTX3060
っていう感じでuse_gpuを使っていたら勝手にGPU1を使用してくれていました。
自分はGPU1を使いたいって感じです。

![image](https://user-images.githubusercontent.com/42853476/196293657-210dded8-0701-43d1-aec1-85fe57c6c452.png)

**Comment by Hiroshiba** [comment]
ありがとうございます！

なにもしない場合GPU 0番が選ばれそうなので、妙ですね･･･。
当て推量なのですが、もしかしたら２枚積みされている関係でエラーが出ているかもと少し思いました。

`Nvidia Optimus`という環境だとGPU 0番が使われて想定外の動作をするという報告もあります。

- https://github.com/VOICEVOX/voicevox_core/issues/309

**Comment by kuroneko6423** [comment]
一部見受けられたバグ(?)
```
INFO:     192.168.1.40:52052 - "POST /audio_query?text=非公開&speaker=8 HTTP/1.1" 200 OK
INFO:     192.168.1.40:52052 - "POST /synthesis?speaker=8 HTTP/1.1" 200 OK
INFO:     192.168.1.40:37290 - "POST /audio_query?text=非公開&&speaker=14 HTTP/1.1" 200 OK
WARNING: convert_pos() in njd2jpcommon.c: 記号 サ変接続 * * are not appropriate POS.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_make() in jcomon_label.c: No phoneme.
INFO:     192.168.1.40:38422 - "POST /audio_query?text=非公開&&speaker=3 HTTP/1.1" 200 OK
INFO:     192.168.1.40:37290 - "POST /synthesis?speaker=14 HTTP/1.1" 200 OK
```

**Comment by takana-v** [comment]
WARNING周りのログはopenjtalk関係のエラーなので、直接この問題には関係しないと思われます。

- `WARNING: JPCommonLabel_make() in jcomon_label.c: No phoneme.`
単語が辞書に登録されていないことなどが原因で、音素に変換した結果が空になった際の警告です。
- `WARNING: convert_pos() in njd2jpcommon.c: 記号 サ変接続 * * are not appropriate POS.`
`記号,サ変接続,*,*`が以下のルール表に登録されていないのが原因です。
`pos-id.def`にも入っていない品詞なのでなぜこのエラーが出るのは謎ですが...
https://github.com/VOICEVOX/open_jtalk/blob/1.11/src/njd2jpcommon/njd2jpcommon_rule_utf_8.h#L54
- `WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.`
`？意味分からない`など、先頭に疑問符が入っている際の警告です。
- `WARNING: JPCommonLabel_insert_pause() in jpcommon_label.c: First mora should not be short pause.`
`？`や`、`など、音素の`pau`に分類されるものが文の先頭に入っていた際の警告です。

また、ログが長い場合は折り畳みを使っていただくと見やすくなるかと思います。
https://qiita.com/tetusan/items/611059bd0836e2fbaaaf

**Comment by kuroneko6423** [comment]
了解です。

**Comment by sevenc-nanashi** [comment]
自分の環境でも再現できました。
synthesisを40回叩いたところでエラーが発生しました。
全体のログ：https://gist.github.com/sevenc-nanashi/bc92dd1714cd69de6c48724870c1baa5

```
Exception: ONNX raise exception: Non-zero status code returned while running MemcpyToHost node. Name:'Memcpy_token_27' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1758)\onnxruntime.dll!00007FFD39D0DE04: (caller: 00007FFD3A10F080) Exception(3) tid(8c04) 887A0006 GPU \x82\xaa\x88ȍ~\x82̃R\x83}\x83\x93\x83h\x82ɉ\x9e\x93\x9a\x82\xb5\x82܂\xb9\x82\xf1\x81B\x8c\xb4\x88\xf6\x82Ƃ\xb5\x82āA\x8cĂяo\x82\xb5\x8c\xb3\x82̃A\x83v\x83\x8a\x83P\x81[\x83V\x83\x87\x83\x93\x82\xa9\x82疳\x8c\xf8\x82ȃR\x83}\x83\x93\x83h\x82\xaa\x93n\x82\xb3\x82ꂽ\x82\xb1\x82Ƃ\xaa\x8dl\x82\xa6\x82\xe7\x82\xea\x82܂\xb7\x81B
```

このエラー部分をがんばってデコードし、sjis化したら「GPU が以降３マンドに応答しせん。原因として、呼び出し元�Aプリケーションから無効なコマンドが渡されたことが考えられす。」（GPU が以降**コ**マンドに応答しせん。原因として、呼び出し元**ア**プリケーションから無効なコマンドが渡されたことが考えられ**ま**す。）という文章が得られました。
<details>
<summary>backslashescapeからのデコード</summary>

```py
In [47]: def try_decode(c):
    ...:     if ord(c) > 256:
    ...:         return c.encode("utf8")
    ...:     else:
    ...:         return c.encode("latin")
```

</details>


環境：
- OS: Windows 10 Pro、21H2 19044.1949
- コミット：9f5a14d6f098a5068ab60e111480b0a042214390
- Python： 3.9.9 64bit
- CPU：Intel Core i5-8400
- GPU：NVIDIA GeForce GTX 750 Ti

専用GPUメモリが1.8 / 2.0GB（共有：3.4 / 8.0GB）とほとんどいっぱいだったので、それが関係しているかもしれません。

**Comment by Hiroshiba** [comment]
UTF-8エラーメッセージでもdecode可能になってメッセージが見えるようになった感じでしょうか！よかったです。

そしてエラーメッセージの内容は･･･謎ですね･･･。

ちなみに @sevenc-nanashi さんの環境はNVIDIA Optimusでしょうか 👀
（タスクマネージャーのパフォーマンスでGPUが２つ見えてたらOptimus環境だと思います。）

**Comment by sevenc-nanashi** [comment]
![image](https://user-images.githubusercontent.com/59691627/197879085-e4c16d22-b932-495d-a2f9-f213566ae2c6.png)
GPUは1枚ですね。

**Comment by Hiroshiba** [comment]
なるほどです！となると、メモリ不足っぽいときに出るというのがたしかに理にかなってそうに感じますね･･･！
（40回実行してからエラーということは、だんだん残りメモリが減ってきてる気がしますね･･･。）

**Comment by kuroneko6423** [comment]
これエラーが出たらSSDの使用率、メモリ使用率、VRAM使用率全部上がる 🤔

**Comment by kuroneko6423** [comment]
これは修正可能なのだろうか()

**Comment by Hiroshiba** [comment]
@kuroneko6423 
２週間ほど前の @sabonerune さんのプルリクエストで直ってるはずですね･･･！

- https://github.com/VOICEVOX/voicevox_engine/pull/490

[こちらのプレリリース](https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.14.0-preview.1)は上記の変更が含まれているはずです。お試しいただければ！

**Comment by kuroneko6423** [comment]
おお？
今から適用します！

**Comment by kuroneko6423** [comment]
これって今のVersion 0.13.3に適用されてますか？

**Comment by kuroneko6423** [comment]
https://voicevox.hiroshiba.jp/
ここにあるインストーラーでやったらなぜか
![image](https://user-images.githubusercontent.com/42853476/200177884-1c4482b0-7cb1-4d64-b6d4-da2165bb40a1.png)
多分表記ミスだと思いますが()

**Comment by Hiroshiba** [comment]
> ここにあるインストーラーでやったらなぜか1.13.2

エンジンのバージョンとエディタのバージョンは必ずしも一致しないという運用になっています。

あと、正式版にはまだリリースされていないので、先程案内した[こちらのプレリリース](https://github.com/VOICEVOX/voicevox_engine/releases/tag/0.14.0-preview.1)をお試しいただければ！

このissueの目的であるUTF-8エラーに関しては解決したと思うのでcloseしたいと思います。
引き続き同じ問題が発生する場合はissueを別の問題が発覚した場合は別のissueをopenしてください。

ありがとうございました！！

**Comment by kuroneko6423** [comment]
```INFO:     192.168.1.40:47396 - "POST /audio_query?text=非公開&speaker=38 HTTP/1.1" 200 OK
2022-11-10 23:11:02.8425568 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running FusedConv node. Name:'Conv_366_Relu_367' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:122 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:116 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-HQR5BSV ; expr=cudaMalloc((void**)&p, size);


INFO:     192.168.1.40:48102 - "POST /synthesis?speaker=35 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\kuroneko\DOCUME~1\voicevox\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "C:\Users\kuroneko\DOCUME~1\voicevox\uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "C:\Users\kuroneko\DOCUME~1\voicevox\fastapi\applications.py", line 208, in __call__
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\applications.py", line 112, in __call__
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\middleware\errors.py", line 159, in __call__
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\middleware\cors.py", line 84, in __call__
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\exceptions.py", line 71, in __call__
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\routing.py", line 656, in __call__
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\routing.py", line 259, in handle
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\routing.py", line 61, in app
  File "C:\Users\kuroneko\DOCUME~1\voicevox\fastapi\routing.py", line 226, in app
  File "C:\Users\kuroneko\DOCUME~1\voicevox\fastapi\routing.py", line 161, in run_endpoint_function
  File "C:\Users\kuroneko\DOCUME~1\voicevox\starlette\concurrency.py", line 39, in run_in_threadpool
  File "C:\Users\kuroneko\DOCUME~1\voicevox\anyio\to_thread.py", line 28, in run_sync
  File "C:\Users\kuroneko\DOCUME~1\voicevox\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
  File "C:\Users\kuroneko\DOCUME~1\voicevox\anyio\_backends\_asyncio.py", line 743, in run
  File "C:\Users\kuroneko\DOCUME~1\voicevox\run.py", line 341, in synthesis
  File "C:\Users\kuroneko\DOCUME~1\voicevox\voicevox_engine\synthesis_engine\synthesis_engine_base.py", line 236, in synthesis
  File "C:\Users\kuroneko\DOCUME~1\voicevox\voicevox_engine\synthesis_engine\synthesis_engine.py", line 483, in _synthesis_impl
  File "C:\Users\kuroneko\DOCUME~1\voicevox\voicevox_engine\synthesis_engine\core_wrapper.py", line 521, in decode_forward
Exception: ONNX raise exception: Non-zero status code returned while running FusedConv node. Name:'Conv_366_Relu_367' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:122 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:116 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=DESKTOP-HQR5BSV ; expr=cudaMalloc((void**)&p, size);

```

**Comment by kuroneko6423** [comment]
これはGPUメモリっぽい？
GPUを2つ同時に使用する方法とかありますか？
