### ISSUE TITLE
README.md: 環境構築の手順が不足してる

### ISSUE THREAD

**Issue by raa0121** [VOICEVOX/voicevox_engine#497]
## 不具合の内容

各環境での python 以外の依存が増えており、インストール方法が無く、新規構築が不能になっている

### 現象・ログ

`python -m pip install -r requirements.txt` および `python -m pip install -r requirements-tests.txt` で pyopenjtalk と pyworld のインストールに外部依存がある。

#### pyopenjtalk のエラーログ
<details>

```
Collecting pyopenjtalk@ git+https://github.com/VOICEVOX/pyopenjtalk@50b0296a9e1b666e5a09a41ec9e9284a2a9b608f
  Cloning https://github.com/VOICEVOX/pyopenjtalk (to revision 50b0296a9e1b666e5a09a41ec9e9284a2a9b608f) to c:\users\raa0121\appdata\local\temp\pip-install-03tfir_b\pyopenjtalk_b92b2a18efc54efab7f6a550ad8d237a
  Running command git clone --filter=blob:none --quiet https://github.com/VOICEVOX/pyopenjtalk 'C:\Users\raa0121\AppData\Local\Temp\pip-install-03tfir_b\pyopenjtalk_b92b2a18efc54efab7f6a550ad8d237a'
  Running command git rev-parse -q --verify 'sha^50b0296a9e1b666e5a09a41ec9e9284a2a9b608f'
  Running command git fetch -q https://github.com/VOICEVOX/pyopenjtalk 50b0296a9e1b666e5a09a41ec9e9284a2a9b608f
  Running command git checkout -q 50b0296a9e1b666e5a09a41ec9e9284a2a9b608f
  Resolved https://github.com/VOICEVOX/pyopenjtalk to commit 50b0296a9e1b666e5a09a41ec9e9284a2a9b608f
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      <string>:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      Traceback (most recent call last):
        File "C:\msys64\home\raa0121\develop\voicevox_engine\.venv39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\msys64\home\raa0121\develop\voicevox_engine\.venv39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\msys64\home\raa0121\develop\voicevox_engine\.venv39\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\raa0121\AppData\Local\Temp\pip-build-env-882j4g16\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\raa0121\AppData\Local\Temp\pip-build-env-882j4g16\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\raa0121\AppData\Local\Temp\pip-build-env-882j4g16\overlay\Lib\site-packages\setuptools\build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\raa0121\AppData\Local\Temp\pip-build-env-882j4g16\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 153, in <module>
        File "F:\Python39\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "F:\Python39\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "F:\Python39\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。
  ----------------------------------------
```

</details>

#### pyworld のログ
<details>

```
Collecting pyworld==0.3.0
  Downloading pyworld-0.3.0.tar.gz (212 kB)
     ---------------------------------------- 212.0/212.0 kB 6.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cython>=0.24.0
  Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
Collecting numpy
  Downloading numpy-1.23.4-cp39-cp39-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 13.3 MB/s eta 0:00:00
Building wheels for collected packages: pyworld
  Building wheel for pyworld (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      C:\Users\raa0121\AppData\Local\Temp\pip-build-env-z7ampvw0\overlay\Lib\site-packages\setuptools\dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\pyworld
      copying pyworld\__init__.py -> build\lib.win-amd64-cpython-39\pyworld
      running build_ext
      skipping 'pyworld\pyworld.cpp' Cython extension (up-to-date)
      building 'pyworld.pyworld' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyworld
Failed to build pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects
```

</details>

#### Windows
python3.8 をインストールし、PATH を通し、`python -m pip install -r requirements.txt` および `python -m pip install -r requirements-tests.txt` を行う

### 期待動作

`python -m pip install -r requirements.txt` および `python -m pip install -r requirements-tests.txt` が成功する

## VOICEVOXのバージョン

master

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

*   Windows 11 Pro 64bit (10.0.22000.1098)

## その他

Windows 以外でも、各種ライブラリが足りないと起きえるので、apt 等でインストールすべきライブラリを羅列するべきだと思います。

**Comment by sabonerune** [comment]
C/C++コンパイラとCMakeが必須ですね。
Windowsの場合は以下のものが必要になります。
- Visual C++ Build Tools(C++によるデスクトップ開発)
- CMake

その他気を付ける点としてはMSVCとCMake両方にPATHが正しく通っている必要があることでしょうか？

Linuxの場合は大抵の場合GCCが最初から入っているのではないのでしょうか？(詳しくない)
そのためビルドツールは不要でCMakeのみが必要です。

あとは環境によってはlibsndfile1が必要なのでしょうか？
- #212

macは持ってないので分からないです。

**Comment by PickledChair** [comment]
> Linuxの場合は大抵の場合GCCが最初から入っているのではないのでしょうか？(詳しくない)

C/C++ の開発環境を利用可能にするのに、apt であれば大抵 `build-essential` を入れる気がします（これなしでも最初から gcc が使えるかどうかはよくわかりません……。環境依存でしょうか？）

> macは持ってないので分からないです。

macOS の場合は C/C++ のコンパイラ (clang) を使えるようにするのに Command Line Tools for Xcode が必要です。CMake は私はパッケージマネージャの Homebrew を使ってインストールしています。

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！

とりあえずCMake・C/C++コンパイラは必ず必要そうですね･･･！
OSごとのインストール方法の案内はけっこう大変なのかなと思いました。
（pyopenjtalkのREADMEにも書かれてない）

いったん、CMakeとC/C++コンパイラが必要であるということだけでも案内して、OSごとの環境構築コマンドはあとあと整備するのもありなのかなと思いました！

**Comment by masinc** [comment]
> いったん、CMakeとC/C++コンパイラが必要であるということだけでも案内して、OSごとの環境構築コマンドはあとあと整備するのもありなのかなと思いました！

とりあえず、案内のためのPR作っちゃいます。

**Comment by Hiroshiba** [comment]
PR作成ありがとうございます！！

これで開発に慣れてる人が開発に参加する障壁は１つ取っ払えたかなと思います。
cmakeのインストール方法に自力でたどり着くのが難しい人向けに案内を書くべきかですが、これはリポジトリの方針によるのかなと思いました。

その方針ですが、より初心者の方に優しくなるべきか、ある程度技術力がある人を想定すべきか、ちょっと判断が難しいところです。
いったんこの形で様子見して、問題の声を聞いたりリポジトリの方針が決まったらまた議論する、ということにして、このissueはいったんcloseでも良いのかなと思いました！

**Comment by raa0121** [comment]
はい、一旦閉じますね。
@masinc PRありがとうございました。
