### ISSUE TITLE
起動してすぐにリクエストするとASGIエラーが出てくる

### ISSUE THREAD

**Issue by kuroneko6423** [VOICEVOX/voicevox_engine#527]
## 質問の内容

APIを起動してすぐにリクエストするとASGIエラーが出てくる

## VOICEVOXのバージョン

0.14.0-preview.2
0.13.3

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

Windows 10 Pro 64bit (10.0.10586)
RTX 3060
DDR3 24GB

## その他

エラーは起動してすぐにsynthesisとaudio_queryをリクエストするとでてくる(?)

<details>
<summary>エラーの一部</summary>

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
WARNING: JPCommonLabel_push_word() in jpcommon_label.c: First mora should not be question flag.
WARNING: JPCommonLabel_insert_pause() in jpcommon_label.c: First mora should not be short pause.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 64, in app
  File "starlette\responses.py", line 139, in __call__
  File "starlette\exceptions.py", line 68, in sender
  File "anyio\streams\memory.py", line 205, in send
anyio.BrokenResourceError
Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=194723.484 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "h11\_state.py", line 249, in _fire_event_triggered_transitions
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\events.py", line 81, in _run
  File "uvicorn\protocols\http\h11_impl.py", line 328, in timeout_keep_alive_handler
  File "h11\_connection.py", line 468, in send
  File "h11\_connection.py", line 493, in send_with_data_passthrough
  File "h11\_connection.py", line 242, in _process_event
  File "h11\_state.py", line 238, in process_event
  File "h11\_state.py", line 251, in _fire_event_triggered_transitions
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

</details>

よくDiscordで言ってた話ですね

**Comment by kuroneko6423** [comment]
これが続くエラー
```
INFO:     192.168.1.41:49420 - "POST /synthesis?speaker=8 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\base.py", line 57, in __call__
  File "anyio\_backends\_asyncio.py", line 567, in __aexit__
  File "starlette\middleware\base.py", line 30, in coro
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 61, in app
  File "fastapi\routing.py", line 226, in app
  File "fastapi\routing.py", line 161, in run_endpoint_function
  File "starlette\concurrency.py", line 39, in run_in_threadpool
  File "anyio\to_thread.py", line 28, in run_sync
  File "anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 743, in run
  File "run.py", line 375, in synthesis
  File "voicevox_engine\synthesis_engine\synthesis_engine_base.py", line 236, in synthesis
  File "voicevox_engine\synthesis_engine\synthesis_engine.py", line 483, in _synthesis_impl
  File "voicevox_engine\synthesis_engine\core_wrapper.py", line 521, in decode_forward
Exception: ONNX raise exception: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp(555)\onnxruntime.dll!00007FF9A41420D8: (caller: 00007FF9A414263C) Exception(2127) tid(1428) 887A0005 GPU \x83f\x83o\x83C\x83X \x83C\x83\x93\x83X\x83^\x83\x93\x83X\x82\xaa\x92\x86\x92f\x82\xb3\x82\xea\x82Ă\xa2\x82܂\xb7\x81BGetDeviceRemovedReason \x82\xf0\x8eg\x97p\x82\xb5\x82ēK\x90؂ȃA\x83N\x83V\x83\x87\x83\x93\x82\xf0\x8am\x94F\x82\xb5\x82Ă\xad\x82\xbe\x82\xb3\x82\xa2\x81B
```

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！

起動直後にリクエスト送るとエラー、なるほどです。
`decode_forward`でエラーが出ていそうですね。また文字化けしていそうですが･･･。

**Comment by kuroneko6423** [comment]
文字化けはどうしましょ()

**Comment by Hiroshiba** [comment]
最高の質問だね！！
文字化けはハッカーが最初に挑戦するよくある課題だ。
僕がよくやっている文字化けの解決策を教えるよ！

まず文字化けしている箇所をよーくチェックして見るんだ。
こんな呪文が書いてあるね。

> Exception: ONNX raise exception: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp(555)\onnxruntime.dll!00007FF9A41420D8: (caller: 00007FF9A414263C) Exception(2127) tid(1428) 887A0005
> GPU \x83f\x83o\x83C\x83X \x83C\x83\x93\x83X\x83^\x83\x93\x83X\x82\xaa\x92\x86\x92f\x82\xb3\x82\xea\x82Ă\xa2\x82܂\xb7\x81BGetDeviceRemovedReason \x82\xf0\x8eg\x97p\x82\xb5\x82ēK\x90؂ȃA\x83N\x83V\x83\x87\x83\x93\x82\xf0\x8am\x94F\x82\xb5\x82Ă\xad\x82\xbe\x82\xb3\x82\xa2\x81B

よし！この文字化けしたものを君の力でもとに戻すんだ！

一番手っ取り早い方法は”その文字をそのままGoogleにぶちこむ”だ！
実際にやってみるとこうなる。

![image](https://user-images.githubusercontent.com/4987327/208310316-b8363d8f-7c31-43f6-a6a4-5187ca4bee26.png)

だいたいこういうのは同じ問題を抱えて解決を試みたハッカーがいるはずだ。
その人と同じことをしよう！
実際さっきの検索結果にハッカーがいるね！
これを見て同じやり方をすれば良いんじゃないかな。

僕はもう答えがわかったよ！君も同じことができれば僕たちの一員だ！
グッドラック！！

**Comment by kuroneko6423** [comment]
とてもグッジョブですねー
グッドラックです!w

**Comment by kuroneko6423** [comment]
デバイス インスタンスが中断されています。GetDeviceRemovedReason を使用して適切なアクションを確認してください。

**Comment by kuroneko6423** [comment]
これは... 🤔

**Comment by kuroneko6423** [comment]
Linux(Ubuntu)でもエラーが出たので張っておきます。
```
INFO:     10.0.0.65:39034 - "POST /audio_query?text=メッセージ非公開&speaker=45 HTTP/1.1" 200 OK
2022-12-29 00:17:50.869655025 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running FusedConv node. Name:'m0.Conv_367' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=server-main ; expr=cudaMalloc((void**)&p, size); 


2022-12-29 00:17:50.869713995 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running If node. Name:'' Status Message: Non-zero status code returned while running FusedConv node. Name:'m0.Conv_367' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=server-main ; expr=cudaMalloc((void**)&p, size); 


INFO:     10.0.0.65:39034 - "POST /synthesis?speaker=45 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/kuroneko/voicevox-nvidia/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
  File "/home/kuroneko/voicevox-nvidia/uvicorn/middleware/proxy_headers.py", line 75, in __call__
  File "/home/kuroneko/voicevox-nvidia/fastapi/applications.py", line 208, in __call__
  File "/home/kuroneko/voicevox-nvidia/starlette/applications.py", line 112, in __call__
  File "/home/kuroneko/voicevox-nvidia/starlette/middleware/errors.py", line 159, in __call__
  File "/home/kuroneko/voicevox-nvidia/starlette/middleware/cors.py", line 84, in __call__
  File "/home/kuroneko/voicevox-nvidia/starlette/exceptions.py", line 71, in __call__
  File "/home/kuroneko/voicevox-nvidia/starlette/routing.py", line 656, in __call__
  File "/home/kuroneko/voicevox-nvidia/starlette/routing.py", line 259, in handle
  File "/home/kuroneko/voicevox-nvidia/starlette/routing.py", line 61, in app
  File "/home/kuroneko/voicevox-nvidia/fastapi/routing.py", line 226, in app
  File "/home/kuroneko/voicevox-nvidia/fastapi/routing.py", line 161, in run_endpoint_function
  File "/home/kuroneko/voicevox-nvidia/starlette/concurrency.py", line 39, in run_in_threadpool
  File "/home/kuroneko/voicevox-nvidia/anyio/to_thread.py", line 28, in run_sync
  File "/home/kuroneko/voicevox-nvidia/anyio/_backends/_asyncio.py", line 805, in run_sync_in_worker_thread
  File "/home/kuroneko/voicevox-nvidia/anyio/_backends/_asyncio.py", line 743, in run
  File "/home/kuroneko/voicevox-nvidia/run.py", line 300, in synthesis
  File "/home/kuroneko/voicevox-nvidia/voicevox_engine/synthesis_engine/synthesis_engine_base.py", line 234, in synthesis
  File "/home/kuroneko/voicevox-nvidia/voicevox_engine/synthesis_engine/synthesis_engine.py", line 483, in _synthesis_impl
  File "/home/kuroneko/voicevox-nvidia/voicevox_engine/synthesis_engine/core_wrapper.py", line 495, in decode_forward
Exception: ONNX raise exception: Non-zero status code returned while running If node. Name:'' Status Message: Non-zero status code returned while running FusedConv node. Name:'m0.Conv_367' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=server-main ; expr=cudaMalloc((void**)&p, size); 


INFO:     10.0.0.79:47098 - "POST /audio_query?text=メッセージ非公開&speaker=3 HTTP/1.1" 200 OK
```

**Comment by Hiroshiba** [comment]
> GetDeviceRemovedReason を使用して適切なアクションを確認してください

なるほどです！！
うーん…。調べても解決策とかは出なさそうですね…。
とりあえず起動後しばらく待ってもらう、というワークアラウンドになりそうです。
（あれ、そもそもしばらく待つとエラーでないんでしたっけ👀）

**Comment by Hiroshiba** [comment]
> Linux(Ubuntu)でもエラーが出たので張っておきます。

報告ありがとうございます！
こちらもこのissueタイトルと同じタイミングで出るエラーですか？

**Comment by kuroneko6423** [comment]
> > Linux(Ubuntu)でもエラーが出たので張っておきます。
> 
> 報告ありがとうございます！ こちらもこのissueタイトルと同じタイミングで出るエラーですか？

しばらく起動して何万リクエスト(?)した後で出ましたね

**Comment by kuroneko6423** [comment]
もしかしたら起動したらすぐにリクエストしたらそうなるかもしれませんが()

**Comment by kuroneko6423** [comment]
> Linux(Ubuntu)でもエラーが出たので張っておきます。
> 
> ```
> INFO:     10.0.0.65:39034 - "POST /audio_query?text=メッセージ非公開&speaker=45 HTTP/1.1" 200 OK
> 2022-12-29 00:17:50.869655025 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running FusedConv node. Name:'m0.Conv_367' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=server-main ; expr=cudaMalloc((void**)&p, size); 
> 
> 
> 2022-12-29 00:17:50.869713995 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running If node. Name:'' Status Message: Non-zero status code returned while running FusedConv node. Name:'m0.Conv_367' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=server-main ; expr=cudaMalloc((void**)&p, size); 
> 
> 
> INFO:     10.0.0.65:39034 - "POST /synthesis?speaker=45 HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/home/kuroneko/voicevox-nvidia/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
>   File "/home/kuroneko/voicevox-nvidia/uvicorn/middleware/proxy_headers.py", line 75, in __call__
>   File "/home/kuroneko/voicevox-nvidia/fastapi/applications.py", line 208, in __call__
>   File "/home/kuroneko/voicevox-nvidia/starlette/applications.py", line 112, in __call__
>   File "/home/kuroneko/voicevox-nvidia/starlette/middleware/errors.py", line 159, in __call__
>   File "/home/kuroneko/voicevox-nvidia/starlette/middleware/cors.py", line 84, in __call__
>   File "/home/kuroneko/voicevox-nvidia/starlette/exceptions.py", line 71, in __call__
>   File "/home/kuroneko/voicevox-nvidia/starlette/routing.py", line 656, in __call__
>   File "/home/kuroneko/voicevox-nvidia/starlette/routing.py", line 259, in handle
>   File "/home/kuroneko/voicevox-nvidia/starlette/routing.py", line 61, in app
>   File "/home/kuroneko/voicevox-nvidia/fastapi/routing.py", line 226, in app
>   File "/home/kuroneko/voicevox-nvidia/fastapi/routing.py", line 161, in run_endpoint_function
>   File "/home/kuroneko/voicevox-nvidia/starlette/concurrency.py", line 39, in run_in_threadpool
>   File "/home/kuroneko/voicevox-nvidia/anyio/to_thread.py", line 28, in run_sync
>   File "/home/kuroneko/voicevox-nvidia/anyio/_backends/_asyncio.py", line 805, in run_sync_in_worker_thread
>   File "/home/kuroneko/voicevox-nvidia/anyio/_backends/_asyncio.py", line 743, in run
>   File "/home/kuroneko/voicevox-nvidia/run.py", line 300, in synthesis
>   File "/home/kuroneko/voicevox-nvidia/voicevox_engine/synthesis_engine/synthesis_engine_base.py", line 234, in synthesis
>   File "/home/kuroneko/voicevox-nvidia/voicevox_engine/synthesis_engine/synthesis_engine.py", line 483, in _synthesis_impl
>   File "/home/kuroneko/voicevox-nvidia/voicevox_engine/synthesis_engine/core_wrapper.py", line 495, in decode_forward
> Exception: ONNX raise exception: Non-zero status code returned while running If node. Name:'' Status Message: Non-zero status code returned while running FusedConv node. Name:'m0.Conv_367' Status Message: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:124 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 2: out of memory ; GPU=0 ; hostname=server-main ; expr=cudaMalloc((void**)&p, size); 
> 
> 
> INFO:     10.0.0.79:47098 - "POST /audio_query?text=メッセージ非公開&speaker=3 HTTP/1.1" 200 OK
> ```

これの重要なこと言い忘れていました。
これになると6期生全員の処理ができなくなります。

**Comment by Hiroshiba** [comment]
なるほどです！
issueタイトルと異なるエラーが出た場合は話題が異なるので、別issueにしてください！
（エラーメッセージが同じ時は関連性があるかもしれないので、同じ場所でも良いと思います）

ちなみにそのエラーは https://github.com/VOICEVOX/voicevox_engine/issues/513 と同じくメモリ不足が原因だと思われます。
（エラーメッセージに PCUDA failure 2: out of memory` とあるので）

なので #513 に書き加えると他の方の助けになるはずです！

**Comment by tarepan** [comment]
同様のバグが長期間報告されていないため、こちらの issue は一旦 close とさせて頂きます (#1063)。同様のバグがあった場合は遠慮なくご連絡ください。
