### ISSUE TITLE
APIサーバとして立てるとvoicevoxが立ち上がらない

### ISSUE THREAD

**Issue by msms70294584** [VOICEVOX/voicevox_engine#693]
isuue立てるの初めてなので、至らない所があればすみません。

## 不具合の内容

APIサーバとしてvoicevox_engineを立ち上げvoicevoxを起動すると、voicevoxのUIが「データ準備中・・・」になったまま立ち上がらない

### 現象・ログ
<details>
INFO:     127.0.0.1:61078 - "GET /version HTTP/1.1" 200 OK
INFO:     127.0.0.1:61078 - "GET /engine_manifest HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\middleware\base.py", line 53, in __call__    async with anyio.create_task_group() as task_group:
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\middleware\base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\middleware\cors.py", line 92, in __call__    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\voicevox_engine-P8L0LCTp\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\voicevox_engine\run.py", line 1045, in engine_manifest
    return engine_manifest_loader.load_manifest()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\voicevox_engine\voicevox_engine\engine_manifest\EngineManifestLoader.py", line 16, in load_manifest
    manifest = EngineManifest(
               ^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for EngineManifest
supported_features -> manage_library
  field required (type=value_error.missing)
</details>

### 再現手順

> python run.py voicevox_dir=%VOICEVOX_DIR% --use_gpu 

で、APIサーバを立ち上げたあとにvoicevoxを
> npm run electron:serve

で起動

### 期待動作

voicevoxが立ち上がる

## VOICEVOXのバージョン

4b296fd22190dc3d011fcc4565e0a6e6eccf2502
(issue立ち上げ時点で最新)

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他
調べてみると、最近のcommitでエラーに関連しているEngineManifestを触っているところがあり、その前のcommitにcheckoutして同じコマンドを流したら、voicevoxが起動しました
ですので、EngineManifestを触っているcommitが原因ではないかと思っています

EngineManifestを触っているコミット
53f4e5fe966bcc08aa84f8bbf96f7ca2aabf0fcc

起動したコミット
9c89689c1a12a8b3a89da53fe0166c00a430cb1c

**Comment by takana-v** [comment]
ご報告ありがとうございます！

私の方で調査してみましたが、原因となったコミットは以下だと思われます。
https://github.com/VOICEVOX/voicevox_engine/commit/8bc4d473feff4178965276c94151e66947c5f66a
ここでEngineManifestに破壊的な変更が入っているのですが、`manifect_version`が変更されていないため、過去バージョンのエンジンを使用した際に、適切にマイグレーションされずエラーが発生しているのかなと思います。

**Comment by takana-v** [comment]
> manifest_versionの更新も確かに必要なのですが、そもそもengine_manifest.jsonをvoicevox_dirから読み込むという状態も間違っているように思います。この仕様を修正し、現状のディレクトリ(engine_root()で得られるパス)から取得するように変更するという方向性で修正するのがいいかなと思いました

確かにこちらの方が良いかもしれません。
（マイグレーション云々の話はエディタ側の話を勘違いしてたかもです）

**Comment by Hiroshiba** [comment]
ユーザーの設定ファイルはマイグレーションが必要だと思います。
manifest.jsonは開発者側の設定ファイルなので、少なくとも自動的にマイグレーションするのは危ない気がしました！
新しいパラメータがなかった時用にデフォルト値を用意してあげるくらいはいいと思います。

`engine_root()`の書き換え周りは特にこだわり無いのでぜひ改良していっていただければ！！
