### ISSUE TITLE
開発環境のインストールおよびデバッグ中に、pyopenjtalkのインストールでエラーが発生しました

### ISSUE THREAD

**Issue by jushe** [VOICEVOX/voicevox_engine#740]
## 質問の内容
Translated by chatgpt3.5
When I try to install the pyopenjtalk, it just report these messages.

pyopenjtalkをインストールしようとすると、これらのメッセージが表示されるだけです。

```
Building wheels `for` collected packages: pyopenjtalk
  Building wheel for pyopenjtalk (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyopenjtalk (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1971 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      running bdist_wheel
      running build
      running build_py
      -- Building version 0.3.0+827a3fc
      creating build
      creating build/lib.linux-x86_64-3.11
      creating build/lib.linux-x86_64-3.11/pyopenjtalk
      copying pyopenjtalk/utils.py -> build/lib.linux-x86_64-3.11/pyopenjtalk
      copying pyopenjtalk/version.py -> build/lib.linux-x86_64-3.11/pyopenjtalk
      copying pyopenjtalk/__init__.py -> build/lib.linux-x86_64-3.11/pyopenjtalk
      creating build/lib.linux-x86_64-3.11/pyopenjtalk/htsvoice
      copying pyopenjtalk/htsvoice/mei_normal.htsvoice -> build/lib.linux-x86_64-3.11/pyopenjtalk/htsvoice
      copying pyopenjtalk/htsvoice/README.md -> build/lib.linux-x86_64-3.11/pyopenjtalk/htsvoice
      copying pyopenjtalk/htsvoice/LICENSE_mei_normal.htsvoice -> build/lib.linux-x86_64-3.11/pyopenjtalk/htsvoice
      running build_ext
      /tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-1khosbqz/pyopenjtalk_322e43451a134a84bf20f9063b4dbcb3/pyopenjtalk/openjtalk/__init__.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      np.import_array()

      cimport cython
      from libc.stdlib cimport calloc

      from openjtalk.mecab cimport Mecab, Mecab_initialize, Mecab_load, Mecab_analysis
      ^
      ------------------------------------------------------------

      pyopenjtalk/openjtalk.pyx:14:0: 'openjtalk/mecab.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      np.import_array()

      cimport cython
      from libc.stdlib cimport calloc

      from openjtalk.mecab cimport Mecab, Mecab_initialize, Mecab_load, Mecab_analysis
      ^
      ------------------------------------------------------------

      pyopenjtalk/openjtalk.pyx:14:0: 'openjtalk/mecab/Mecab.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      np.import_array()

      cimport cython
      from libc.stdlib cimport calloc

      from openjtalk.mecab cimport Mecab, Mecab_initialize, Mecab_load, Mecab_analysis
      ^
      ------------------------------------------------------------

      pyopenjtalk/openjtalk.pyx:14:0: 'openjtalk/mecab/Mecab_initialize.pxd' not found

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      np.import_array()

      cimport cython
      from libc.stdlib cimport calloc

      from openjtalk.mecab cimport Mecab, Mecab_initialize, Mecab_load, Mecab_analysis
      ^
      ------------------------------------------------------------

      ......(I delete some message to show in this issue)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              "utf-8",
              "-t",
              "utf-8",
              path
          ]
          mecab_dict_index(10, argv)    ^
      ------------------------------------------------------------

      pyopenjtalk/openjtalk.pyx:290:4: 'mecab_dict_index' is not a constant, variable or function identifier
      Compiling pyopenjtalk/openjtalk.pyx because it changed.
      [1/1] Cythonizing pyopenjtalk/openjtalk.pyx
      Traceback (most recent call last):
        File "/root/anaconda3/envs/voicevox/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/anaconda3/envs/voicevox/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/anaconda3/envs/voicevox/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 264, in <module>
          setup(
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "setup.py", line 64, in build_extensions
          build_ext.build_extensions(self)
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-bfbzdeks/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyopenjtalk/openjtalk.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyopenjtalk
Failed to build pyopenjtalk
```

## VOICEVOXのバージョン

0.15.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [×] WSL

WSL on windows
Ubuntu 22.04.1 LTS

**Comment by Hiroshiba** [comment]
I'm not sure what the root cause is here...
I checked the issues on the original pyopenjtalk repository, and I didn't find any similar reports, so this might be a unique case.
https://github.com/r9y9/pyopenjtalk

---

ちょっと原因が分かりませんね・・・。
本家のpyopenjtalkのissueを見てみても同じような報告はなかったので、特殊な事例なのかもしれません。
https://github.com/r9y9/pyopenjtalk

**Comment by jushe** [comment]
> 

Can I install the origin pyopenjtalk instead of the modify one?(pyopenjtalk @ git+https://github.com/VOICEVOX/pyopenjtalk@acd4f02d2af3129382c151590238b9370465e360 ;) 
Only when I install form the "requirements.txt", it shows these error.

---
元のpyopenjtalkを修正版の代わりにインストールできますか？（pyopenjtalk @ git+https://github.com/VOICEVOX/pyopenjtalk@acd4f02d2af3129382c151590238b9370465e360 ;)
"requirements.txt"からインストールした場合のみ、これらのエラーが表示されます。

> I'm not sure what the root cause is here... I checked the issues on the original pyopenjtalk repository, and I didn't find any similar reports, so this might be a unique case. https://github.com/r9y9/pyopenjtalk
> 
> ちょっと原因が分かりませんね・・・。 本家のpyopenjtalkのissueを見てみても同じような報告はなかったので、特殊な事例なのかもしれません。 https://github.com/r9y9/pyopenjtalk

**Comment by Hiroshiba** [comment]
You might lose access to some features like the user dictionary, but it may be possible to use the original pyopenjtalk instead.

---

ユーザー辞書機能など一部の機能が使えなくなりますが、オリジナルのpyopenjtalkを用いることも可能かもしれません。

**Comment by jushe** [comment]
> @jushe
> 
> > ## VOICEVOXのバージョン
> > 0.15.0
> 
> Which commit is `0.15.0`? This error is probably due to Cython3.0 and I think it was fixed with #717 [9b04dc9](https://github.com/VOICEVOX/voicevox_engine/commit/9b04dc9f5ac0b12561843343a002562f82f5353b).
> 
> `0.15.0`とはどこのコミットでしょうか? このエラーは恐らくCython3によるもので #717 [9b04dc9](https://github.com/VOICEVOX/voicevox_engine/commit/9b04dc9f5ac0b12561843343a002562f82f5353b) で修正したと思います。

Well, I thought I use the latest version and the latest release version is 0.15.0-preview.4.
But it seems that I was wrong. After updating my local vocievox version it can be worked now. Thank you. 
---
最新バージョンを使用していたと思いましたが、最新のリリースバージョンは0.15.0-preview.4のようです。しかし、私は間違っていたようです。ローカルのvoicevoxバージョンを更新した後、問題なく動作するようになりました。ありがとうございます。
