### ISSUE TITLE
Linuxで「sndfile library not found」が出る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_engine#745]
## 不具合の内容

Linuxで「sndfile library not found」が出ることがあります。
（解決済みなのですが案内を兼ねてissue作ってみました）

### 現象・ログ

Linuxで製品版エンジンを動かすとこのようなエラーが出ることがあります。

```bash
$ ./run 
Traceback (most recent call last):
  File "run.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "soundfile.py", line 142, in <module>
OSError: sndfile library not found
[19930] Failed to execute script 'run' due to unhandled exception!
```

### 再現手順

voicevox_engineのリリースからwgetして7zで解凍

## その他

Discordで報告をいただきました
https://discord.com/channels/879570910208733277/879628718455283722/1149883380532514887

**Comment by Hiroshiba** [comment]
↓で解決します
```bash
apt-get install libsndfile1
```
